// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-3zqE_G_1xGsKKbRzAE-eh988tok-qfM',
    appId: '1:33306441539:web:41dac4f6439fb467eb21f6',
    messagingSenderId: '33306441539',
    projectId: 'medistock-pharmacy-v001',
    authDomain: 'medistock-pharmacy-v001.firebaseapp.com',
    storageBucket: 'medistock-pharmacy-v001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJPv98vF19iydqn1lSL5xCOOZ4imXmbK0',
    appId: '1:33306441539:android:64410157d3ff1a5ceb21f6',
    messagingSenderId: '33306441539',
    projectId: 'medistock-pharmacy-v001',
    storageBucket: 'medistock-pharmacy-v001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd7t3makfN8oxvMmPs6naNriLQs-seSzs',
    appId: '1:33306441539:ios:a530d90bcb20f84eeb21f6',
    messagingSenderId: '33306441539',
    projectId: 'medistock-pharmacy-v001',
    storageBucket: 'medistock-pharmacy-v001.firebasestorage.app',
    iosBundleId: 'com.example.medistock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd7t3makfN8oxvMmPs6naNriLQs-seSzs',
    appId: '1:33306441539:ios:a530d90bcb20f84eeb21f6',
    messagingSenderId: '33306441539',
    projectId: 'medistock-pharmacy-v001',
    storageBucket: 'medistock-pharmacy-v001.firebasestorage.app',
    iosBundleId: 'com.example.medistock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-3zqE_G_1xGsKKbRzAE-eh988tok-qfM',
    appId: '1:33306441539:web:f3f62e9190a2320eeb21f6',
    messagingSenderId: '33306441539',
    projectId: 'medistock-pharmacy-v001',
    authDomain: 'medistock-pharmacy-v001.firebaseapp.com',
    storageBucket: 'medistock-pharmacy-v001.firebasestorage.app',
  );
}
